# Generated by Django 3.2.16 on 2023-10-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
