# Generated by Django 3.2.16 on 2024-06-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kali', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='header',
            field=models.ImageField(blank=True, upload_to='headers/'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='no_ai_tag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='CommissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='C:/static/main/img/404.jpg', upload_to='')),
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kali.commission')),
            ],
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kali.art')),
            ],
        ),
    ]
