# Generated by Django 3.2.16 on 2024-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kali', '0002_auto_20231030_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
