# Generated by Django 3.2.16 on 2024-04-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kali', '0003_alter_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='art',
            field=models.ImageField(default='C:/static/main/img/404.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
