version: '3.8'
services:
  # web:
  #   build:
  #     context: ./kali
  #     dockerfile: ./Dockerfile
  #   # command: gunicorn kali.wsgi --bind 0.0.0.0:8000 --workers 4 --worker-class gevent --timeout 300 --preload 
  #   command: python manage.py runserver 8000
  #   volumes:
  #     - ./volumes/static_volume:/usr/src/kali/staticfiles
  #     - ./kali/:/usr/src/kali/
  #   expose:
  #     - 8000
  #   env_file:
  #     ./.env
  #   depends_on:
  #     - db
  #   restart: always
  
  db:
    image: postgres:15.3
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=postgres
    env_file:
      - .env
    ports:
      - '8088:5432'
    restart: always

  # nginx:
  #   image: nginx:1.23
  #   build: 
  #     context: ./nginx
  #     dockerfile: ./Dockerfile
  #   volumes:
  #   - ./volumes/static_volume:/home/staticfiles
  #   ports:
  #     - 8085:80
  #   depends_on:
  #     - web
  #   restart: always

  # react:
  #   build: ./react
  #   dockerfile: ./Dockerfile


